### ISSUE TITLE
How to get the datasets?

### ISSUE THREAD

**Issue by SudaYDD** [VILAN-Lab/PBREC-MT#1]
Thanks a lot for your work! How to get the datasets?

**Comment by VILAN-Lab** [comment]
referring expression comprehension annotations from:    https://github.com/lichengunc/refer
and this is the link
https://bvisionweb1.cs.unc.edu/licheng/referit/data/refclef.zip
https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco.zip
https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco+.zip
https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcocog.zip

photos are from https://cocodataset.org/#home
and the link is : http://images.cocodataset.org/zips/train2014.zip.
hope that will be helpful.

**Comment by VILAN-Lab** [comment]
> Thanks a lot for your work! How to get the datasets?

referring expression comprehension annotations from: https://github.com/lichengunc/refer
and this is the link
https://bvisionweb1.cs.unc.edu/licheng/referit/data/refclef.zip
https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco.zip
https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco+.zip
https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcocog.zip

photos are from https://cocodataset.org/#home
and the link is : http://images.cocodataset.org/zips/train2014.zip.
hope that will be helpful.
