### ISSUE TITLE
ModuleNotFoundError: No module named 'models.visual_model.clip'

### ISSUE THREAD

**Issue by Issac304** [VILAN-Lab/PBREC-MT#3]
there no have this module in your code?

**Comment by Issac304** [comment]
![8bf89a5ee545c1d8ca0e8f676b867ce](https://github.com/user-attachments/assets/08a37823-3c72-4686-8263-c4c50c285fba)

**Comment by MiracleOct** [comment]
> there no have this module in your code?

I meet the same situation when running train.sh ...
"""
 ModuleNotFoundError: No module named 'models.visual_model.clip' 
Traceback (most recent call last):
  File "train.py", line 16, in <module>
"""
It seems that clip.py is lost in visual_model directory, can you please provide it?

**Comment by Juniper1021** [comment]
This is an unwanted code. We will fix it later

**Comment by william1111111111** [comment]
Please accept our apologies for the delay. 
We have now uploaded the most recent version of the code along with an updated README. Additionally, we have completed debugging on our local server, and the system is ready for standard training procedures. @MiracleOct @Issac304

**Comment by MiracleOct** [comment]
> Please accept our apologies for the delay. We have now uploaded the most recent version of the code along with an updated README. Additionally, we have completed debugging on our local server, and the system is ready for standard training procedures. @MiracleOct @Issac304

Thanks a lot! I try to run the newest code immediately when you upload, unfortunately, there is still some problem in my Linux system(some errors about BERT). It seems that the requirement.txt is incomplete, and I also don't sure about the version of python. T_T
By the way, I'm also a student in Guangxi University. My tutor let me read this article, and I'm eagar to run this program successfully and to acquire relevant knowledge. If you still in school, can I consult you in school when you are convenient?

**Comment by william1111111111** [comment]
This is the file tree in the pythonProject which is not shown in the github.
    --bert
    ----bert-base-uncased
    ------bert_config.json
    ------pytorch_model.bin
    --checkpoints
    ----detr-r101.pth
    --data(refcoco dataset put here)
    --ln_data
    ----other
    ------images
    --------train2014
    ----------*******(photos here)

As for BERT, it can be downloaded from the Transformers library (something like from_pretrained('bert-base-uncased')).
For the data, you can download it via the instructions provided at 
[https://github.com/djiajunustc/TransVG/blob/main/docs/GETTING_STARTED.md](url).
For code learning, our project is based on TransVG [https://github.com/djiajunustc/TransVG/tree/main](url) and maybe you can also reproduce their code.
If you have any questions, you can leave a message below this project, and I will get back to you as soon as I see   @MiracleOct 

For the environment, I used 'pip list' to show the packages, but note that it may include many packages that are not being used.


Package                  Version
------------------------ ------------
accelerate               0.25.0
addict                   2.4.0
asttokens                2.4.1
backcall                 0.2.0
boto3                    1.34.4
botocore                 1.34.4
certifi                  2023.11.17
charset-normalizer       3.3.2
contourpy                1.1.1
cycler                   0.12.1
Cython                   3.0.7
decorator                5.1.1
executing                2.0.1
filelock                 3.13.1
fonttools                4.47.0
fsspec                   2023.12.2
grad-cam                 1.5.0
h5py                     3.10.0
huggingface-hub          0.20.1
idna                     3.6
imageio                  2.33.1
importlib-metadata       7.0.1
importlib-resources      6.1.1
ipython                  8.12.3
jedi                     0.19.1
Jinja2                   3.1.2
jmespath                 1.0.1
joblib                   1.3.2
kiwisolver               1.4.5
lazy_loader              0.3
loralib                  0.1.1
markdown-it-py           3.0.0
MarkupSafe               2.1.3
matplotlib               3.7.4
matplotlib-inline        0.1.6
mdurl                    0.1.2
mmcv                     2.2.0
mmengine                 0.10.3
mpmath                   1.3.0
networkx                 3.1
ninja                    1.11.1.1
numpy                    1.24.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
opencv-python            4.8.1.78
opencv-python-headless   4.5.5.64
packaging                23.2
parso                    0.8.3
peft                     0.7.1
pexpect                  4.9.0
pickleshare              0.7.5
Pillow                   10.1.0
pip                      23.3.1
platformdirs             4.1.0
prompt-toolkit           3.0.43
psutil                   5.9.7
ptyprocess               0.7.0
pure-eval                0.2.2
pycocotools              2.0.7
Pygments                 2.17.2
pyparsing                3.1.1
python-dateutil          2.8.2
pytorch-pretrained-bert  0.6.2
PyWavelets               1.4.1
PyYAML                   6.0.1
regex                    2023.10.3
requests                 2.31.0
rich                     13.7.0
s3transfer               0.9.0
safetensors              0.4.1
scikit-image             0.21.0
scikit-learn             1.3.2
scipy                    1.10.1
setuptools               68.2.2
six                      1.16.0
stack-data               0.6.3
sympy                    1.12
termcolor                2.4.0
threadpoolctl            3.3.0
tifffile                 2023.7.10
timm                     0.4.9
tokenizers               0.15.0
tomli                    2.0.1
torch                    1.13.0+cu117
torchaudio               0.13.0+cu117
torchvision              0.14.0+cu117
tqdm                     4.64.0
traitlets                5.14.1
transformers             4.36.2
triton                   2.1.0
ttach                    0.0.3
typing_extensions        4.9.0
urllib3                  1.26.18
wcwidth                  0.2.12
wheel                    0.41.2
yacs                     0.1.8
yapf                     0.40.2
zipp                     3.17.0

**Comment by MiracleOct** [comment]
Thank you so much! I'm weak foundation so it's a little difficult for me to run the project smoothly, so maybe some of my questions are naive. Thanks to your patient reply, I will retry next!

**Comment by Issac304** [comment]
thank you so much！
